freebsd_instance:
  image_family: freebsd-12-1

freebsd_task:
  name: $TOOLCHAIN x86_64-unknown-freebsd
  env:
    matrix:
        # we seem to be broken on rust 1.53 https://github.com/benfred/py-spy/pull/407
      - TOOLCHAIN: 1.52.1
    GITHUB_TOKEN: ENCRYPTED[67283c0b5c9880ac3b7d8fb0335c4b24f95c62dab30b5379dca192600801c380a41f7436c7daaebfaa8f1381237a8412]
  setup_script:
    - pkg install -y curl bash python
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain $TOOLCHAIN
  build_script:
    - $HOME/.cargo/bin/rustup run $TOOLCHAIN cargo build --verbose --release
  test_script:
    - $HOME/.cargo/bin/rustup run $TOOLCHAIN cargo test --verbose --release
  publish_script:
    - bash ./ci/publish_freebsd.sh
