repos:
      - repo: https://github.com/codespell-project/codespell
        rev: v2.2.4
        hooks:
        - id: codespell
          additional_dependencies: [tomli]
          args: ["--toml", "pyproject.toml"]
          exclude: (?x)^(ci/testdata.*|images.*)$
      - repo: https://github.com/doublify/pre-commit-rust
        rev: v1.0
        hooks:
#        - id: fmt
        - id: cargo-check
