# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "../../", "/code/py-spy"
  config.vm.provision :shell, path: "install.sh"
  config.vm.provision :shell, path: "build_wheels.sh", run: 'always'
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
