Vagrant.configure("2") do |config|
  config.vm.define "fbsd_12_2" do |fbsd_12_2|
    fbsd_12_2.vm.box = "rbspy/FreeBSD-12.2-STABLE"
  end
  config.vm.define "fbsd_13_1" do |c|
    c.vm.box = "rbspy/FreeBSD-13.1-STABLE"
  end

  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__exclude: [".git", ".vagrant.d"]

  config.vm.provision "shell", inline: <<~SHELL
    pkg install -y python devel/llvm90
  SHELL

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end
